version: "3"
services:
  es:
    image: elasticsearch:7.17.1
    container_name: es
    environment:
       - discovery.type=single-node
    ports:
       - 9200:9200

  web:
    build: .
    container_name: uksc-search-app
    depends_on:
      - es
    ports:
      - 8501:8501
