apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: es
  name: es
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: es
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: es
    spec:
      containers:
        - env:
            - name: discovery.type
              value: single-node
          image: uksc-elasticsearch
          name: es
          ports:
            - containerPort: 9200
          resources: {}
      restartPolicy: Always
status: {}
